### ISSUE TITLE
For whom is it written?

### ISSUE THREAD

**Issue by borodadada** [scrawl/smaa-opengl#1]
How can you spread such examples ? It does not really run . Inside, there is no SFML. I dont know you version. New version dont work. Damn why all people create complicate things.

**Comment by Yours3lf** [comment]
hi there,

smaa is not an easy effect, so at this stage you are pretty much expected to solve such simple things. 
Anyways, here's a version w/ all dependencies, should work fine under windows.
One thing though, now I'm on nvidia, and the effect is only correct when I run it under nvidia nsight. No idea why. The source is a bit different, since I wanted to debug under nvidia nsight.
https://drive.google.com/file/d/0B33Sh832pOdOdUZ0cDRfT0lieWs/view?usp=sharing
